#!/usr/bin/env python3
"""抖音视频文案提取器 — Playwright方案 v3 (2026-07-10)
用法: python3 douyin-extractor.py <video_id1> [video_id2] ...

功能:
  1. 启动Playwright Chromium无头浏览器(复用context)
  2. 手机设备模拟(iPhone UA + touch支持)
  3. 依次访问多个抖音视频页面
  4. 点击"展开"按钮获取完整描述
  5. 提取页面文本+标题+Meta描述
  6. 保存cookies供yt-dlp后续使用(下载音频→Whisper转录)
  7. 输出JSON结果到stdout

限制:
  - 只能获取页面可见文本(标题/描述/合集目录)
  - 完整口播文案需: 登录cookies→yt-dlp下载音频→faster-whisper转录
  - 服务器IP若被抖音列入黑名单，所有方法(包括第三方API)均失败

完整方法栈(按优先级):
  ① Playwright浏览器自动化 — 当前方案，获取标题+描述+合集
  ② yt-dlp + 登录态cookies — 有cookies后可下载音频→Whisper转录
  ③ 第三方解析API — anxinxia.com等工具(需非黑名单IP)
  ④ 主题级缺口分析 — 无文案时的替代方案(从标题推断主题范围)
"""
import json, sys
from playwright.sync_api import sync_playwright

def extract_all(video_ids):
    """批量提取视频信息，复用浏览器context(手机设备模拟)"""
    results = []

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            args=['--no-sandbox', '--disable-blink-features=AutomationControlled']
        )
        context = browser.new_context(
            user_agent='Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
            viewport={'width': 390, 'height': 844},
            device_scale_factor=3,
            is_mobile=True,
            has_touch=True,
            locale='zh-CN',
            timezone_id='Asia/Shanghai',
        )

        for vid in video_ids:
            url = f"https://www.douyin.com/video/{vid}"
            page = context.new_page()
            r = {"id": vid, "title": "", "meta_desc": "", "page_text": [], "expanded": False}

            try:
                page.goto(url, wait_until='domcontentloaded', timeout=20000)
                page.wait_for_timeout(4000)

                r["title"] = page.title()

                # 点"展开"按钮
                try:
                    expand = page.locator('text=展开')
                    if expand.is_visible(timeout=2000):
                        expand.click()
                        page.wait_for_timeout(1000)
                        r["expanded"] = True
                except:
                    pass

                # 页面文本
                body = page.evaluate("() => document.body.innerText")
                if body:
                    lines = [l.strip() for l in body.split('\n') if l.strip() and len(l) > 5]
                    r["page_text"] = lines[:40]

                # Meta描述
                meta = page.evaluate("() => document.querySelector('meta[name=\"description\"]')?.content || ''")
                r["meta_desc"] = meta

            except Exception as e:
                r["error"] = str(e)

            results.append(r)
            print(f"  ✅ {vid}: {r.get('title','')[:60]}", file=sys.stderr)
            page.close()

        # 保存cookies到文件(供yt-dlp下载音频→Whisper转录)
        cookie_file = "/tmp/douyin_cookies.txt"
        cookies = context.cookies()
        with open(cookie_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n# Generated by douyin-extractor.py\n\n")
            for c in cookies:
                domain = c.get('domain', '.douyin.com')
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                f.write(f"{domain}\t{flag}\t{c.get('path','/')}\t{'TRUE' if c.get('secure') else 'FALSE'}\t{int(c.get('expires',0))}\t{c['name']}\t{c['value']}\n")
        print(f"  🍪 {len(cookies)} cookies saved to {cookie_file}", file=sys.stderr)

        browser.close()

    return results

if __name__ == '__main__':
    ids = sys.argv[1:] if len(sys.argv) > 1 else ["7660080439630294985"]
    results = extract_all(ids)
    print(json.dumps(results, ensure_ascii=False, indent=2))
